### ISSUE TITLE
Strange error on windows

### ISSUE THREAD

**Issue by alexander-akait** [wooorm/unified-args#10]
Command: `remark '{**/*,*}.md' -i .gitignore -f -q`
```shell
[lint:remark ] Error: No input
[lint:remark ]     at stdin (C:\projects\webfont\node_modules\remark-cli\node_modules\unified-args\node_modules\unified-engine\lib\file-set-pipeline\stdin.js:49:10)
[lint:remark ]     at wrapped (C:\projects\webfont\node_modules\remark-cli\node_modules\unified-args\node_modules\unified-engine\node_modules\trough\index.js:128:19)
[lint:remark ]     at next (C:\projects\webfont\node_modules\remark-cli\node_modules\unified-args\node_modules\unified-engine\node_modules\trough\index.js:81:24)
[lint:remark ]     at done (C:\projects\webfont\node_modules\remark-cli\node_modules\unified-args\node_modules\unified-engine\node_modules\trough\index.js:163:12)
[lint:remark ]     at C:\projects\webfont\node_modules\remark-cli\node_modules\unified-args\node_modules\unified-engine\lib\file-set-pipeline\file-system.js:91:7
[lint:remark ]     at C:\projects\webfont\node_modules\remark-cli\node_modules\unified-args\node_modules\unified-engine\lib\finder.js:173:7
[lint:remark ]     at C:\projects\webfont\node_modules\remark-cli\node_modules\unified-args\node_modules\unified-engine\node_modules\vfile-find-down\index.js:84:5
[lint:remark ]     at next (C:\projects\webfont\node_modules\remark-cli\node_modules\unified-args\node_modules\unified-engine\node_modules\vfile-find-down\index.js:181:7)
[lint:remark ]     at visitAll (C:\projects\webfont\node_modules\remark-cli\node_modules\unified-args\node_modules\unified-engine\node_modules\vfile-find-down\index.js:174:3)
[lint:remark ]     at find (C:\projects\webfont\node_modules\remark-cli\node_modules\unified-args\node_modules\unified-engine\node_modules\vfile-find-down\index.js:83:10)
[lint:remark ] 
[lint:remark ] npm ERR! Windows_NT 6.3.9600
[lint:remark ] npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "lint:remark"
[lint:remark ] npm ERR! node v4.6.2
[lint:remark ] npm ERR! npm  v2.15.11
[lint:remark ] npm ERR! code ELIFECYCLE
[lint:remark ] npm ERR! webfont@7.0.1 lint:remark: `remark '{**/*,*}.md' -i .gitignore -f -q`
[lint:remark ] npm ERR! Exit status 1
[lint:remark ] npm ERR! 
[lint:remark ] npm ERR! Failed at the webfont@7.0.1 lint:remark script 'remark '{**/*,*}.md' -i .gitignore -f -q'.
[lint:remark ] npm ERR! This is most likely a problem with the webfont package,
[lint:remark ] npm ERR! not with npm itself.
[lint:remark ] npm ERR! Tell the author that this fails on your system:
[lint:remark ] npm ERR!     remark '{**/*,*}.md' -i .gitignore -f -q
[lint:remark ] npm ERR! You can get information on how to open an issue for this project with:
[lint:remark ] npm ERR!     npm bugs webfont
[lint:remark ] npm ERR! Or if that isn't available, you can get their info via:
[lint:remark ] npm ERR! 
[lint:remark ] npm ERR!     npm owner ls webfont
[lint:remark ] npm ERR! There is likely additional logging output above.
[lint:remark ] 
[lint:remark ] npm ERR! Please include the following file with any support request:
[lint:remark ] npm ERR!     C:\projects\webfont\npm-debug.log
ERROR: "lint:remark" exited with 1.
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "lint"
npm ERR! node v4.6.2
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE
npm ERR! webfont@7.0.1 lint: `npm-run-all -l --parallel lint:*`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the webfont@7.0.1 lint script 'npm-run-all -l --parallel lint:*'.
npm ERR! This is most likely a problem with the webfont package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm-run-all -l --parallel lint:*
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs webfont
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls webfont
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     C:\projects\webfont\npm-debug.log
npm ERR! Test failed.  See above for more details.
Command exited with code 1
```

**Comment by wooorm** [comment]
Thanks for reporting! Are there markdown files? If so, where are they?

**Comment by alexander-akait** [comment]
@wooorm 
>  Are there markdown files?

Yes.

> If so, where are they?

In root project directory (README.md and CHANGELOG.md)

**Comment by alexander-akait** [comment]
@wooorm https://github.com/itgalaxy/webfont package

**Comment by wooorm** [comment]
Is the error on your system or on appveyor or something?
Also: can you show me what `npm run lint:remark` with an env variable: `DEBUG="*"`?

**Comment by alexander-akait** [comment]
@wooorm 
> on appveyor

Yep, I'm going to try now.

**Comment by alexander-akait** [comment]
@wooorm https://ci.appveyor.com/project/evilebottnawi/webfont/build/job/ngrwg0vk4k0rojlc

**Comment by wooorm** [comment]
This looks like it’s glob support on windows.
Maybe it’s the slash in `{**/*,*}.md`, which works on Unix but not on Windows, but I’d guess minimatch downstream should be able to handle that.
I \*think\* it looks like a problem in node-glob or minimatch, but I’m not entirely sure.

As a fix: why not use `remark . -i .gitignore -f -q`? I think that should work.

**Comment by alexander-akait** [comment]
@wooorm thanks, now I try your example and try to find out whose is it error :smile:

**Comment by wooorm** [comment]
@evilebottnawi Were you able to find something out?

**Comment by alexander-akait** [comment]
@wooorm no, in this week i have time to do this, i close this issue, if trouble be in `unified-args`, i mention you in this issue

**Comment by wooorm** [comment]
Cheers, thanks for checking!
